name: "NestJS Build App"
description: "Perform the build and test of the NestJS App"

inputs:
  AZURE_SP:
    description: "Credentials of the Azure SP"
    required: true
  NODE_VERSION:
    description: "NodeJS Version"
    required: false
    default: "22.14.0"
  WORKING_DIR:
    description: "Directory where the app is located"
    required: true

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_SP }}

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{inputs.NODE_VERSION}}

    - run: npm i
      working-directory: ${{inputs.WORKING_DIR}}
      shell: bash

    - run: npm run build
      working-directory: ${{inputs.WORKING_DIR}}
      shell: bash
    # - run: npm test
    #   shell: bash

    - name: Create deployment zip artifact
      run: |
        # Navigate into the backend folder to zip its contents
        cd ${{inputs.WORKING_DIR}}
        zip -r deploy.zip dist node_modules package.json package-lock.json
        # The 'deploy.zip' will be created inside the 'backend' folder
      shell: bash

    # - uses: montudor/action-zip@v1
    #   with:
    #     args: zip -qq -r app.zip . -i dist package.json package-lock.json node_modules
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: deploy.zip
        path: ${{inputs.WORKING_DIR}}/deploy.zip
        retention-days: 5
