name: "Deploy NestJS app"
description: "Perform the deployment of NestJS app into App Service"

inputs:
  AZURE_SP:
    description: "Credentials of the Azure SP"
    required: true
  AZURE_CLI_VERSION:
    description: "Azure cli version"
    required: false
    default: "latest"
  STORAGE_ACCOUNT_NAME:
    description: "Name of the storage account"
    required: true
  STAGE:
    description: "Deployment stage"
    required: true
  WORKING_DIR:
    description: "Directory where the app is located"
    required: false
    default: "./"

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_SP }}

    - name: Download a single artifact
      uses: actions/download-artifact@v4
      with:
        name: deploy

    - name: Download ${{ inputs.STAGE }} output from Storage
      uses: azure/CLI@v1
      with:
        azcliversion: ${{ inputs.AZURE_CLI_VERSION }}
        inlineScript: |
          az storage blob download \
          --file ${{ inputs.STAGE }}.json \
          --name ${{ inputs.STAGE }}.json \
          --account-name ${{ inputs.STORAGE_ACCOUNT_NAME }} \
          --container-name output

    - name: Show directory
      run: ls -ltr
      working-directory: ${{ inputs.WORKING_DIR }}
      shell: bash

    - name: Read ${{ inputs.STAGE }}.json
      run: cat ${{ inputs.STAGE }}.json
      working-directory: ${{ inputs.WORKING_DIR }}
      shell: bash

    - name: Read ${{ inputs.STAGE }}.json
      run: |
        # Read the JSON file
        # Assuming terraform_outputs.json is in the root of your repository or downloaded to '.'
        TERRAFORM_OUTPUTS=$(cat ${{ inputs.STAGE }}.json)

        # Create a temporary file with the modified content
        tail -n +2 ${{ inputs.STAGE }}.json > temp-${{ inputs.STAGE }}.json

        # Overwrite the original file with the content of the temporary file
        mv temp-${{ inputs.STAGE }}.json ${{ inputs.STAGE }}.json

        # Create a temporary file with the modified content
        head -n -4 ${{ inputs.STAGE }}.json > temp-${{ inputs.STAGE }}.json

        # Overwrite the original file with the content of the temporary file
        mv temp-${{ inputs.STAGE }}.json ${{ inputs.STAGE }}.json

        TERRAFORM_OUTPUTS=$(cat ${{ inputs.STAGE }}.json)

        # Extract a specific output using jq
        # For a simple string output:
        RESOURCE_GROUP_NAME=$(echo "$TERRAFORM_OUTPUTS" | jq -r '.app_service.value.resource_group_name')
        WEB_APP_NAME=$(echo "$TERRAFORM_OUTPUTS" | jq -r '.app_service.value.web_app_name')

        # Set the extracted value as a step output
        echo "resource_group_name=$RESOURCE_GROUP_NAME" >> "$GITHUB_OUTPUT"
        echo "web_app_name=$WEB_APP_NAME" >> "$GITHUB_OUTPUT"

        echo "Extracted Resource Group Name App Hostname: $RESOURCE_GROUP_NAME"
        echo "Extracted Web App Hostname: $WEB_APP_NAME"
      working-directory: ${{ inputs.WORKING_DIR }}
      shell: bash

    - name: Display Parsed Outputs
      run: |
        echo "Web App Name from previous step: ${{ steps.parse_outputs.outputs.web_app_name }}"
      shell: bash

    - name: Deploy to Azure Web App
      id: deploy-webapp # Give this step an ID to potentially get outputs if needed
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.parse_outputs.outputs.web_app_name }} # e.g., my-nestjs-app-unique
        package: ./deploy.zip # Path to your .zip file relative to the repo root
        # Optionally, specify the startup command if it's different or for clarity
        startup-command: "npm run start:prod"

    