name: 'Build NestJS App'
on:
  workflow_dispatch:

jobs:
  build_app:
    name: "Build NodeJS App"
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    environment: ${{ matrix.stage }}
    defaults:
     run:
       shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/node-build"
      with:
        WORKING_DIR: "./backend"

  terraform_deploy:
    uses: ./.github/workflows/terraform-deploy.yml
