name: '1 - Build NestJS App'
on:
  workflow_dispatch:
    inputs:
      # Define an input for the 'stage'
      stage:
        description: 'Select the deployment stage'
        required: true # Make it required so the user must select one
        default: 'dev' # Set 'dev' as the default option
        type: choice
        options:       # Provide the list of available options
          - dev
          - test
          - prod
  # NEW TRIGGER: Trigger on push to the 'dev' branch
  push:
    branches:
      - dev 
  pull_request:
    branches:
      - main
    

jobs:
  build_app:
    name: "Build NodeJS App"
    strategy:
      matrix:
        stage:  
          - ${{ github.event_name == 'workflow_dispatch' && inputs.stage || (github.event_name == 'push' && github.ref_name == 'dev' && 'dev') || (github.event_name == 'push' && github.ref_name == 'main' && 'prod') || (github.event_name == 'pull_request' && 'dev') }}

    runs-on: ubuntu-latest
    environment: ${{ matrix.stage }}
    defaults:
     run:
       shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/created-stage-file"
      with:
        ENVIRONMENT: ${{ matrix.stage }}

    - uses: "./.github/actions/node-build"
      with:
        WORKING_DIR: "./backend"
