name: '3 - Deploy NestJS App'
on:
  workflow_dispatch:
    inputs:
      # Define an input for the 'stage'
      stage:
        description: 'Select the deployment stage'
        required: true # Make it required so the user must select one
        default: 'dev' # Set 'dev' as the default option
        type: choice
        options:       # Provide the list of available options
          - dev
          - test
          - prod
  workflow_run:
    workflows: ["2 - Terraform Deploy"] # Name of the producer workflow
    types:
      - completed # Trigger when the producer workflow completes

jobs:
  deploy_app:
    # Permissions are crucial for downloading artifacts from another workflow run
    permissions:
      contents: read # Required to checkout the repository
      actions: read  # Required to read workflow run artifacts
    
    name: "Deploy NestJS"
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    environment: ${{ matrix.stage }}
    defaults:
      run:
        shell: bash
           # We keep Terraform files in the terraform directory.
        working-directory: ./terraform-live
    steps:
    - uses: actions/checkout@v3
    
    - uses: "./.github/actions/node-deploy"
      with:
        AZURE_SP: ${{ secrets.AZURE_SP }}
        STORAGE_ACCOUNT_NAME: "tf${{ matrix.stage }}lso01"
        STAGE: "${{ matrix.stage }}"
