name: 'Terraform Deploy'
on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  STA_RESOURCE_GROUP_NAME: rg-tfstate
  RESOURCE_GROUP_LOCATION: westeurope

jobs:
  tfsec:
    name: "Aquasec TfSec"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: TfSec on modules
        run: |
          docker pull aquasec/tfsec:latest
          docker run --rm -v "$(pwd)/infra/modules/linux-web-app:/src" aquasec/tfsec ./src
          docker rmi "aquasec/tfsec:latest" -f | true

      - name: TfSec on terraform files
        run: |
          docker pull aquasec/tfsec:latest
          docker run --rm -v "$(pwd)/infra/environment/${{ matrix.stage }}:/src" aquasec/tfsec ./src
          docker rmi "aquasec/tfsec:latest" -f | true

  build_app:
    name: "Build NodeJS App"
    needs: tfsec
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    environment: ${{ matrix.stage }}
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.

    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/node-build"
      with:
        WORKING_DIR: "./infra/environment/${{ matrix.stage }}"
        AZURE_SP: ${{ secrets.AZURE_SP }}

  plan:
    name: "Plan Job"
    needs: tfsec
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    concurrency: ${{ matrix.stage }}
    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/azure-backend"
      with:
        AZURE_SP: ${{ secrets.AZURE_SP }}
        RESOURCE_GROUP_NAME: "${{ env.STA_RESOURCE_GROUP_NAME }}-${{ matrix.stage }}"
        RESOURCE_GROUP_LOCATION: ${{ env.RESOURCE_GROUP_LOCATION }}
        TAGS: '"UseCase=Terraform" "Stage=${{ matrix.stage }}" "RunNumber=${{ github.run_number }}"'
        STORAGE_ACCOUNT_NAME: "tf${{ matrix.stage }}lso01"
        ENVIRONMENT: ${{ matrix.stage }}

    - uses: "./.github/actions/terraform-plan"
      with:
        WORKING_DIR: "./infra/environment/${{ matrix.stage }}"
        AZURE_SP: ${{ secrets.AZURE_SP }}
        RESOURCE_GROUP_NAME: "${{ env.STA_RESOURCE_GROUP_NAME }}-${{ matrix.stage }}"
        STORAGE_ACCOUNT_NAME: "tf${{ matrix.stage }}lso01"
        CONTAINER_NAME: "states"
        STATE_FILE: "${{ matrix.stage }}.tfstate"
        STAGE: "${{ matrix.stage }}"

  apply:
    name: "Apply Job"
    needs: plan
    strategy:
      matrix:
        stage: [dev]
    runs-on: ubuntu-latest
    environment: ${{ matrix.stage }}
    defaults:
     run:
       shell: bash
       # We keep Terraform files in the terraform directory.
       working-directory: ./terraform-live
    steps:
    - uses: actions/checkout@v3

    - uses: "./.github/actions/terraform-apply"
      with:
        WORKING_DIR: "./infra/environment/${{ matrix.stage }}"
        AZURE_SP: ${{ secrets.AZURE_SP }}
        STORAGE_ACCOUNT_NAME: "tf${{ matrix.stage }}lso01"
        STAGE: "${{ matrix.stage }}"
        CREATE_OUTPUT: "true"